# Generated by Django 6.0.7 on 2026-07-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='especificaciones',
            field=models.TextField(blank=True, help_text='Puedes escribir características detalladas del producto.', verbose_name='Especificaciones Técnicas'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción Corta'),
        ),
    ]
