# Generated by Django 6.0.7 on 2026-07-31 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_especificaciones_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='etiqueta',
            field=models.CharField(choices=[('NINGUNO', 'Sin etiqueta'), ('NUEVO', 'Nuevo'), ('OFERTA', 'En Oferta'), ('AGOTADO', 'Agotado')], default='NINGUNO', max_length=10, verbose_name='Etiqueta / Estado'),
        ),
    ]
