# Generated by Django 6.0.7 on 2026-08-02 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_producto_etiqueta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/', verbose_name='Imagen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Imagen adicional',
                'verbose_name_plural': 'Galería de imágenes',
            },
        ),
    ]
