# Generated by Django 6.0.7 on 2026-08-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_imagenproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Empresa S.A.C.', max_length=100, verbose_name='Nombre de la empresa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/', verbose_name='Logo de la empresa')),
            ],
            options={
                'verbose_name': 'Configuración de la Empresa',
                'verbose_name_plural': 'Configuración de la Empresa',
            },
        ),
    ]
