# Generated by Django 6.0.7 on 2026-08-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_configuracionempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionempresa',
            name='nombre',
            field=models.CharField(default='MegaBit', max_length=100, verbose_name='Nombre de la empresa'),
        ),
    ]
