# Generated by Django 6.0.7 on 2026-08-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_alter_configuracionempresa_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='configuracionempresa',
            name='nombre',
            field=models.CharField(default='Mi Empresa S.A.C.', max_length=100, verbose_name='Nombre de la empresa'),
        ),
    ]
